# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title: "Henryk Chan's Homepage"
description: "Henryk's Homepage "
repository: "Henryk07/henryk07.github.io"
google_scholar_stats_use_cdn: false

# google analytics
google_analytics_id: # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification: 1IIYHWBsQq4ufmy4N6Omkj5MpZp-636QkzmKNYeH5H4 # get google_site_verification from https://search.google.com/search-console/about
bing_site_verification: # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification: # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name: "Henryk Chan \n\ (Haolin Chen)"
  avatar: "images/avater.jpg"
  bio: "BEng MRes AMIMechE"
  location: "London, UK"
  employer:
  pubmed:
  googlescholar: "https://scholar.google.com/citations?user=Yu9lHQgAAAAJ"
  email: "henrykchan.chl@gmail.com"
  researchgate: "https://www.researchgate.net/profile/Henryk-Chan-2"
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "Henryk07"
  google_plus:
  keybase:
  instagram:
  impactstory: # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm:
  linkedin: "henrykchanchl"
  dblp: # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid: "https://orcid.org/0000-0003-3310-5880"
  pinterest:
  soundcloud:
  stackoverflow: # http://stackoverflow.com/users/123456/username
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:
  wikipedia:

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
